# Model Architecture
model:
  n_layers: 6
  d_model: 512
  d_ff: 2048
  n_heads: 8
  dropout_prob: 0.1
  max_padding_train: 50
  max_padding_test: 50


# Training Configuration
training:
  batch_size: 32
  shuffle: true
  epochs: 20
  learning_rate:
    base: 1.0
    warmup_steps: 3000
  accumulation_steps: 10
  random_seed: 42
  label_smoothing: 0.1
# Dataset Configurations
dataset:
  name: "toy"  # Options: wmt14, m30k, wmt24
  language_pair: ["de", "en"]
  size: 10000  # max dataset size to use # TODO: rename to max_size
  test_size: 5000
  cache: true    # whether to cache preprocessed data
  download: true


# Tokenizer Configuration
tokenizer:
  cache: true    # whether to cache tokenizers

# Logging Configuration
logging:
  artifacts_dir: "artifacts"
  subdirs:
    models: "saved_models"
    data: "saved_data"
    tokenizers: "saved_tokenizers"
    loss_curves: "loss_curves"

# Hardware Configuration
hardware:
  device: "cuda"  # Options: cuda, cpu, mps
  data_parallel: false  # CUDA-only; keep false on Mac (MPS)

# Translation Configuration
translation:
  batch_limit: 1000

extras: # extra config options
  harvard: false
